SELECT T001W.MANDT AS Client_MANDT, T001W.WERKS AS Plant_WERKS,
  NAME1 AS Name_NAME1, T001W.BWKEY AS ValuationArea_BWKEY,
  KUNNR AS CustomerNumberOfPlant_KUNNR, T001W.LIFNR AS  VendorNumberOfPlant_LIFNR,
  FABKL AS FactoryCalendarKey_FABKL, T001W.NAME2 AS Name2_NAME2,
  STRAS AS StreetAndHouseNumber_STRAS, T001W.PFACH AS PoBox_PFACH,
  PSTLZ AS PostalCode_PSTLZ, T001W.ORT01 AS City_ORT01,
  EKORG AS PurchasingOrganization_EKORG
FROM T001W
ORDER BY MANDT
